name: Node.js CI

on:
  push:
    branches: [ main ] # Adjust branches as needed
  pull_request:
    branches: [ main ] # Adjust branches as needed

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x] # Test on relevant Node versions

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: Install Dependencies
      run: npm ci # Use ci for clean installs in CI
      
    # Optional: Add linting step
    # - name: Lint
    #   run: npm run lint 
      
    # Optional: Add build step to catch build errors
    # - name: Build
    #   run: npm run build
      
    - name: Run Tests
      run: npm test 